name: Run OCI Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create OCI Private Key
        env:
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
        run: |
          printf '%s\n' "$OCI_PRIVATE_KEY" > "$GITHUB_WORKSPACE/key.pem"
          chmod 600 "$GITHUB_WORKSPACE/key.pem"

          echo "Private key file created:"
          ls -l "$GITHUB_WORKSPACE/key.pem"

      - name: Run OCI Diagnostics
        run: php debug.php
        env:
          OCI_REGION: eu-frankfurt-1
          OCI_USER_ID: ${{ secrets.OCI_USER_OCID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_COMPARTMENT_ID: ${{ secrets.OCI_COMPARTMENT_OCID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_PRIVATE_KEY_FILENAME: ${{ github.workspace }}/key.pem
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_OCID }}
