name: Run OCI Bot

on:
  workflow_dispatch:
  schedule:
- cron: '3,8,13,18,23,28,33,38,43,48,53,58 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create OCI Private Key
        env:
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
        run: |
          printf '%s\n' "$OCI_PRIVATE_KEY" > "$GITHUB_WORKSPACE/key.pem"
          chmod 600 "$GITHUB_WORKSPACE/key.pem"

      - name: Run OCI Bot
        run: php index.php
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_OCID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_PRIVATE_KEY_FILENAME: ${{ github.workspace }}/key.pem
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_OCID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_OCID }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}

          OCI_SHAPE: VM.Standard.A1.Flex
          OCI_OCPUS: '4'
          OCI_MEMORY_IN_GBS: '24'
          OCI_MAX_INSTANCES: '1'
